### ISSUE TITLE
Idea: Make more popular paths more readable

### ISSUE THREAD

**Issue by stephanemagnenat** [dustalov/ballcone#105]
Currently the "Most popular path" section is not super readable, because for every path the day is shown. I think a way to make that more readable would be to show the day only once, like this:
```
        path 1
day 1   path 2
        path 3
--------------
        path 1
day 2   path 2
        path 3
```

The same comment applies to the "Most popular browser" section, but there I believe plots might be better (because browsers do not vanish from one day to the other) (see #104).

**Comment by dustalov** [comment]
Thank you, it is a good idea. I added grouping, so it is more convenient now.
